version: "3"

services:
  pihole-dot-doh:
    container_name: pihole-doh
    image: eltonk/pihole-doh:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      # This activates the DoH feature. If you comment on this, the Pi-hole will only act as blocking ads.
      PIHOLE_DNS_: '127.0.0.1#5053'
      # Set your timezone
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'password123' #change the admin password, otherwise the default password is 'password123'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
